apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.fullname" . }}-gateway
  labels:
    {{ include "nats.labels" . | nindent 4 }}
  {{- if .Values.gateway.service.annotations }}
  annotations:
{{ toYaml .Values.gateway.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- if and (eq .Values.gateway.service.type "LoadBalancer") .Values.gateway.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: gateway
      name: cluster
      {{- if and (eq .Values.gateway.service.type "NodePort") (not (empty .Values.gateway.service.nodePort)) }}
      nodePort: {{ .Values.gateway.service.nodePort  }}
      {{- end }}
  selector:
    {{ include "nats.labels.selector" . | nindent 4 }}
