apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.fullname" . }}-monitoring
  labels:
    {{ include "nats.labels" . | nindent 4 }}
  {{- if .Values.monitoring.service.annotations }}
  annotations:
{{ toYaml .Values.monitoring.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.monitoring.service.type }}
  {{- if and (eq .Values.monitoring.service.type "LoadBalancer") .Values.monitoring.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.monitoring.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.monitoring.service.port }}
      targetPort: monitoring
      name: monitoring
      {{- if and (eq .Values.monitoring.service.type "NodePort") (not (empty .Values.monitoring.service.nodePort)) }}
      nodePort: {{ .Values.monitoring.service.nodePort  }}
      {{- end }}
  selector:
    {{ include "nats.labels.selector" . | nindent 4 }}
